services:
  db:
    image: postgres:15
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: orderdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d orderdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
