name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports: [5432:5432]
        env:
          POSTGRES_DB: orderdb_test
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: devpass
        options: >-
          --health-cmd="pg_isready -U dev -d orderdb_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and run tests
        run: ./mvnw -B verify

